import 'dotenv/config';
import './seeds/theme.seed';
import './seeds/categorie.seed';
import './seeds/question.seed';
import './seeds/reponse.seed';
import './seeds/entreprise.seed';
import './seeds/recommandation.seed';
import './seeds/interpretation.seed';
import './seeds/evaluation.seed';
